### ISSUE TITLE
Extension should test DOM source, not URL.

### ISSUE THREAD

**Issue by karlgroves** [tenon-io/Tenon-Check#2]
Right now this tests based on URL, which is fine, but to really be useful it should shoot a copy of the DOM over to Tenon using the 'src' parameter. This way it can be used on stuff under development.

**Comment by lhtdesignde** [comment]
+1 for this one. Is there any change this might be built?

**Comment by karlgroves** [comment]
Right now I do not plan on getting to this for a while. But if anyone feels like taking this on I will gladly merge the pull request

**Comment by karlgroves** [comment]
Closing. This work is done, however there's currently a bug that will be fixed shortly and the fix will be deployed to Chrome webstore
